baseurl = "https://budougumi0617.github.io/"
languageCode = "ja-jp"
weight = 1
title = "My External Storage"
publishDir = "public"
theme= "hugo-bootstrap-premium"
hasCJKLanguage = true
enableemoji = true
paginate = 10
paginatePath = "page"
disqusShortname = "http-budougumi0617-github-io"

[permalinks]
    post = "/:year/:month/:day/:filename/"
    code = "/:filename/"

[taxonomies]
    tag = "tags"
    topic = "topics"
    category = "categories"

[author]
    name = "budougumi0617"
    email = "budougumi[at]gmail.com"

#
# All parameters below here are optional and can be mixed and matched.
#

# bootswatch theme name, unmark and select one: cerulean, cosmo, cyborg, darkly,
# default, flatly, journal,  lumen, paper, readable, sandstone, simplex,
# slate, spacelab, superhero, united, yeti.

[params.theme]
    name = "flatly"

[params]
    BrandImage = "/logo.png"
    brand = "My External Storage"
    topline = "budougumi0617 の技術ブログです。"
    footline = "Copyright&copy; <a href='/2017/07/11/about-this-site/'>budougumi0617</a>"
    showRightSidebar = true
    googleAnalytics = "UA-43042615-4"
    # sumomeid = ""
    highlight = "default"
    twitter  = "budougumi0617"
    linkedin = "yoichiro-shimizu-19579976"
    github   = "budougumi0617"
    # customCSS = ["/css/.css"]

[[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = -200
    pre = "<i class='fa fa-home'></i>"

[[menu.main]]
    name = "Archives"
    identifier = "archives"
    url = "/post/"
    weight = -180
    pre = "<i class='fa fa-archive'></i>"

[[menu.main]]
    name = "About"
    identifier = ""
    url = "//2017/07/11/about-this-site/"
    weight = -100
    pre = "<i class='fa fa-info-circle'></i>"
